[pytest]
addopts = --cov=src/betadecay-analysis --cov-report=term-missing
testpaths = tests
pythonpath = src/betadecay-analysis
filterwarnings =
    ignore:Read the `app_url` setting:DeprecationWarning:wandb
    ignore:The `Scope.user` setter is deprecated:DeprecationWarning:wandb
