import subprocess
from pathlib import Path
from typing import Any

import ROOT as M


def get_reader(geometry_file: str, sim_file: str) -> tuple[Any, Any]:
    """Initialize MEGAlib readers for the .sim file and its paired .tra file.

    If the .tra file doesn't exist next to the .sim, it's generated by
    invoking ``revan`` with default parameters.
    """
    M.gSystem.Load("$(MEGALIB)/lib/libMEGAlib.so")
    G = M.MGlobal()
    G.Initialize()

    Geometry = M.MDGeometryQuest()
    if not Geometry.ScanSetupFile(M.MString(geometry_file)):
        raise RuntimeError(f"Could not load geometry {geometry_file}")

    Reader = M.MFileEventsSim(Geometry)
    if not Reader.Open(M.MString(sim_file)):
        raise RuntimeError(f"Could not open simulation file {sim_file}")

    tra_file = Path(sim_file).with_suffix(".tra")
    if not tra_file.exists():
        cmd = ["revan", "-g", geometry_file, "-f", sim_file, "-n", "-a"]
        subprocess.run(cmd, check=True)

    TraReader = M.MFileEventsTra()
    if not TraReader.Open(M.MString(str(tra_file))):
        raise RuntimeError(f"Could not open reconstructed file {tra_file}")

    return Reader, TraReader
