likelihoods:
  energy:
    n_std: 1

  arm:
    sigma_x: 4.0
    n_sigma_cos_theta_kin: 1

  posterior:
    alpha_energy: 1.0
    alpha_arm: 1.0
    alpha_anni: 1.0
    alpha_kn: 1.0
    p_bdecay: 1.0
    p_bg: 1.0
